In [4]:
a = 3
print(len(dir(a)))
dir(a)[-10:]

74


['bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'is_integer',
 'numerator',
 'real',
 'to_bytes']

In [3]:
dir(23)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'is_integer',
 

In [5]:
points = [[0,1],[10,6],[7,3]]
points

[[0, 1], [10, 6], [7, 3]]

In [61]:
from random import randint
num_points = 10
x_range = (0,10)
y_range = (0,50)
points = [[randint(*x_range), randint(*y_range)] for _ in range(num_points)]
points

[[10, 0],
 [10, 29],
 [8, 16],
 [0, 16],
 [1, 50],
 [7, 44],
 [3, 46],
 [10, 9],
 [10, 17],
 [0, 45]]

In [2]:
import numpy as np
points = np.array(points)
points

NameError: name 'points' is not defined

In [63]:
num_dim = 2
num_points = 10
x_range = (0,11)
y_range = (0,51)
points = np.random.randint(
    low = (x_range[0], y_range[0]), high = (x_range[1], y_range[1]), size = (num_points,num_dim)
)
points

array([[ 3, 22],
       [ 2, 37],
       [ 7,  1],
       [ 4, 18],
       [ 4, 13],
       [ 5, 40],
       [ 8, 18],
       [ 5,  4],
       [ 7, 37],
       [ 7, 13]])

# COMPARANDO O TEMPO DE EXECUÇÃO ENTRE O PYTHON E O NUMPY

In [64]:
num_dims = 2
num_points = 100000
x_range = (0,10)
y_range = (0,50)

In [80]:
%timeit \
points = [[randint(*x_range),randint(*y_range)] for _ in range(num_points)]

488 ms ± 5.13 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [81]:
%timeit \
points = np.random.randint(low = (x_range[0],y_range[0]),high=(x_range[1],y_range[1]),size=(num_points,num_dims))

2.3 ms ± 16 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### FUNÇÕES BÁSICAS DOO NUMPY

In [82]:
#CONVERTER LISTAS PARA ARRAYS
py_list = [1,2,3,4,5,6,7,8,9,10]
np_array = np.array(py_list)
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
py_list = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
np_array = np.array(py_list)
np_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [100]:
#SLICING(: ele pega todas as linhas de uma coluna) E INDEXAR
print("Primeira linha: \t\t\t{}\n".format(np_array[0]))
print("Primeira linha: \t\t\t{}\n".format(np_array[0,:]))
print("Primeira coluna: \t\t\t{}\n".format(np_array[:,0]))
print("Primeira coluna: \t\t\t{}\n".format(np_array[1,:]))
print("Elemento da 3 linha e 2 coluna \t\t\t{}".format(np_array[2,1]))
print("Ultimas 2 linhas e ultimas 2 colunas \t\t\t\n{}\n".format(np_array[1:,1:]))
print("2rd linha e 2rd coluna \t\t\t{}\n".format(np_array[1:1:]))
print("Array com a 1rd e 3rd coluna \t\t\t\n{}\n".format(np_array[:,[0,2]]))


Primeira linha: 			[1 2 3]

Primeira linha: 			[1 2 3]

Primeira coluna: 			[ 1  4  7 10]

Primeira coluna: 			[4 5 6]

Elemento da 3 linha e 2 coluna 			8
Ultimas 2 linhas e ultimas 2 colunas 			
[[ 5  6]
 [ 8  9]
 [11 12]]

2rd linha e 2rd coluna 			[]

Array com a 1rd e 3rd coluna 			
[[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]]



### Atributos básicos dos Arrays Numpy

In [101]:
print("Data type: \t{}".format(np_array.dtype))
print("Array shape: \t{}".format(np_array.shape))

Data type: 	int32
Array shape: 	(4, 3)


### Sequencias de arrays: arranjo

In [10]:
import numpy as np
array=[1,2,3,4,5,6,7,8,9]
array = np.arange(5,9,1,dtype=np.int64)
array

array([5, 6, 7, 8], dtype=int64)

### Arrays de zero

In [12]:
zeros = np.zeros((2,3), dtype=np.int64)
zeros

array([[0, 0, 0],
       [0, 0, 0]], dtype=int64)

### ARRAYS DE UM

In [14]:
um = np.ones((2,3), dtype=np.int64)
um

array([[1, 1, 1],
       [1, 1, 1]], dtype=int64)

### array de constantes

In [15]:
pi = np.full((2,3), 3.14)
pi

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

### MATRIZ IDENTIDE

In [17]:
id = np.eye(5, dtype=np.float32)
id

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)

In [21]:
a = np.sqrt(9)
a

3.0

### Reshape array

In [34]:
array = np.arange(0,10,dtype=int)
array = array.reshape(2,5)
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])